const APARTMENTS = [
    {
        aptName: "Aertson Midtown",
        squareFeet: 2300,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2000,
    },
    {
        aptName: "Aertson Midtown",
        squareFeet: 662,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 1725,
    },
    {
        aptName: "Aertson Midtown",
        squareFeet: 825,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 2091,
    },
    {
        aptName: "Kenect",
        squareFeet: 1110,
        numBeds: 3,
        numBaths: 3,
        startingPrice: 1468,
    },
    {
        aptName: "Kenect",
        squareFeet: 551,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 2500,
    },
    {
        aptName: "Kenect",
        squareFeet: 360,
        numBeds: 0,
        numBaths: 1,
        startingPrice: 1822,
    },
    {
        aptName: "Artemis Midtown",
        squareFeet: 504,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 1399,
    },
    {
        aptName: "Artemis Midtown",
        squareFeet: 1038,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2500,
    },
    {
        aptName: "Artemis Midtown",
        squareFeet: 662,
        numBeds: 0,
        numBaths: 1,
        startingPrice: 1300,
    },
    {
        aptName: "Apollo Midtown",
        squareFeet: 663,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 1695,
    },
    {
        aptName: "Apollo Midtown",
        squareFeet: 968,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2588,
    },
    {
        aptName: "Apollo Midtown",
        squareFeet: 1090,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2740,
    },
    {
        aptName: "Elliston 23",
        squareFeet: 692,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 1800,
    },
    {
        aptName: "Elliston 23",
        squareFeet: 1079,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2600,
    },
    {
        aptName: "Elliston 23",
        squareFeet: 1219,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2700,
    },
    {
        aptName: "Acklen West End",
        squareFeet: 655,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 1703,
    },
    {
        aptName: "Acklen West End",
        squareFeet: 963,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2448,
    },
    {
        aptName: "Acklen West End",
        squareFeet: 963,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2458,
    }
];

export default APARTMENTS;