const APARTMENTS = [
    {
        apartmentName: "Aertson Midtown",
        squareFeet: 2300,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2000,
        url: "https://www.aertsonmidtown.com/",
    },
    {
        apartmentName: "Aertson Midtown",
        squareFeet: 662,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 1725,
        url: "https://www.aertsonmidtown.com/",
    },
    {
        apartmentName: "Aertson Midtown",
        squareFeet: 825,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 2091,
        url: "https://www.aertsonmidtown.com/",
    },
    {
        apartmentName: "Kenect",
        squareFeet: 1110,
        numBeds: 3,
        numBaths: 3,
        startingPrice: 1468,
        url: "https://www.kenectnashville.com/",
    },
    {
        apartmentName: "Kenect",
        squareFeet: 551,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 2500,
        url: "https://www.kenectnashville.com/",
    },
    {
        apartmentName: "Kenect",
        squareFeet: 360,
        numBeds: 0,
        numBaths: 1,
        startingPrice: 1822,
        url: "https://www.kenectnashville.com/",
    },
    {
        apartmentName: "Artemis Midtown",
        squareFeet: 504,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 1399,
        url: "https://www.artemismidtown.com/",
    },
    {
        apartmentName: "Artemis Midtown",
        squareFeet: 1038,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2500,
        url: "https://www.artemismidtown.com/",
    },
    {
        apartmentName: "Artemis Midtown",
        squareFeet: 662,
        numBeds: 0,
        numBaths: 1,
        startingPrice: 1300,
        url: "https://www.artemismidtown.com/",
    },
    {
        apartmentName: "Apollo Midtown",
        squareFeet: 663,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 1695,
        url: "https://www.apollomidtown.com/",
    },
    {
        apartmentName: "Apollo Midtown",
        squareFeet: 968,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2588,
        url: "https://www.apollomidtown.com/",
    },
    {
        apartmentName: "Apollo Midtown",
        squareFeet: 1090,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2740,
        url: "https://www.apollomidtown.com/",
    },
    {
        apartmentName: "Elliston 23",
        squareFeet: 692,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 1800,
        url: "https://www.elliston23apts.com/",
    },
    {
        apartmentName: "Elliston 23",
        squareFeet: 1079,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2600,
        url: "https://www.elliston23apts.com/",
    },
    {
        apartmentName: "Elliston 23",
        squareFeet: 1219,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2700,
        url: "https://www.elliston23apts.com/",
    },
    {
        apartmentName: "Acklen West End",
        squareFeet: 655,
        numBeds: 1,
        numBaths: 1,
        startingPrice: 1703,
        url: "https://www.acklenwestend.com/",
    },
    {
        apartmentName: "Acklen West End",
        squareFeet: 963,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2448,
        url: "https://www.acklenwestend.com/",
    },
    {
        apartmentName: "Acklen West End",
        squareFeet: 963,
        numBeds: 2,
        numBaths: 2,
        startingPrice: 2458,
        url: "https://www.acklenwestend.com/",
    }
];

export default APARTMENTS;